#!/usr/bin/env bash
#that groups visitors by IP and HTTP status code, and displays this data.
aawk '{key=$1" "$9; count[key]++}
END {
    for (i in count)
        print count[i], i
}' apache-access.log | sort -nr -k1,1 -k2,2 -k3,3
