#!/usr/bin/env bash
#that groups visitors by IP and HTTP status code, and displays this data.
awk '{count[$1" "$9]++}
END {
    for (i in count)
        print count[i], i
}' apache-access.log | sort -k1,1nr -k2,2 -k3,3
